package edu.ndsu.eci.international_capstone_exchange.persist.auto;

import org.apache.cayenne.CayenneDataObject;

import edu.ndsu.eci.international_capstone_exchange.persist.Proposal;

/**
 * Class _PairingCompany was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PairingCompany extends CayenneDataObject {

    public static final String COMPANY_ADDRESS_PROPERTY = "companyAddress";
    public static final String COMPANY_NAME_PROPERTY = "companyName";
    public static final String COMPANY_URL_PROPERTY = "companyUrl";
    public static final String PROPOSAL_PROPERTY = "proposal";

    public static final String PK_PK_COLUMN = "pk";

    public void setCompanyAddress(String companyAddress) {
        writeProperty("companyAddress", companyAddress);
    }
    public String getCompanyAddress() {
        return (String)readProperty("companyAddress");
    }

    public void setCompanyName(String companyName) {
        writeProperty("companyName", companyName);
    }
    public String getCompanyName() {
        return (String)readProperty("companyName");
    }

    public void setCompanyUrl(String companyUrl) {
        writeProperty("companyUrl", companyUrl);
    }
    public String getCompanyUrl() {
        return (String)readProperty("companyUrl");
    }

    public void setProposal(Proposal proposal) {
        setToOneTarget("proposal", proposal, true);
    }

    public Proposal getProposal() {
        return (Proposal)readProperty("proposal");
    }


}
