package edu.ndsu.eci.international_capstone_exchange.persist.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import edu.ndsu.eci.international_capstone_exchange.persist.Pairing;
import edu.ndsu.eci.international_capstone_exchange.persist.User;

/**
 * Class _PairingNotes was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PairingNotes extends CayenneDataObject {

    public static final String ADMIN_ONLY_PROPERTY = "adminOnly";
    public static final String NOTE_PROPERTY = "note";
    public static final String TMSTAMP_PROPERTY = "tmstamp";
    public static final String PAIRING_PROPERTY = "pairing";
    public static final String USER_PROPERTY = "user";

    public static final String PK_PK_COLUMN = "pk";

    public void setAdminOnly(Boolean adminOnly) {
        writeProperty("adminOnly", adminOnly);
    }
    public Boolean getAdminOnly() {
        return (Boolean)readProperty("adminOnly");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setTmstamp(Date tmstamp) {
        writeProperty("tmstamp", tmstamp);
    }
    public Date getTmstamp() {
        return (Date)readProperty("tmstamp");
    }

    public void setPairing(Pairing pairing) {
        setToOneTarget("pairing", pairing, true);
    }

    public Pairing getPairing() {
        return (Pairing)readProperty("pairing");
    }


    public void setUser(User user) {
        setToOneTarget("user", user, true);
    }

    public User getUser() {
        return (User)readProperty("user");
    }


}
