package edu.ndsu.eci.international_capstone_exchange.persist.auto;

import org.apache.cayenne.CayenneDataObject;

import edu.ndsu.eci.international_capstone_exchange.persist.User;
import edu.ndsu.eci.international_capstone_exchange.util.UserRole;

/**
 * Class _Role was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Role extends CayenneDataObject {

    public static final String ROLE_PROPERTY = "role";
    public static final String USER_PROPERTY = "user";

    public static final String PK_PK_COLUMN = "pk";

    public void setRole(UserRole role) {
        writeProperty("role", role);
    }
    public UserRole getRole() {
        return (UserRole)readProperty("role");
    }

    public void setUser(User user) {
        setToOneTarget("user", user, true);
    }

    public User getUser() {
        return (User)readProperty("user");
    }


}
